name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  SHOULD_DEPLOY: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') }}

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    outputs:
      should_deploy: ${{ steps.deployment.outcome == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run eslint
      - run: npm run test
      - name: Debug webhook URL
        run: |
          echo "Webhook URL length: ${#DISCORD_WEBHOOK}"
          echo "First 30 chars: ${DISCORD_WEBHOOK:0:30}"
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      # - run: npm run build
      # - name: Install Playwright Browsers
      #   run: npx playwright install --with-deps
      # - name: Run Playwright tests
      #   run: npx playwright test
      # - uses: actions/upload-artifact@v4
      #   if: ${{ !cancelled() }}
      #   with:
      #     name: playwright-report
      #     path: playwright-report/
      #     retention-days: 30
      # - uses: superfly/flyctl-actions/setup-flyctl@master
      #   if: ${{ env.SHOULD_DEPLOY == 'true' }}
      # - id: deployment
      #   run: flyctl deploy --remote-only
      #   if: ${{ env.SHOULD_DEPLOY == 'true' }}
      #   env:
      #     FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - if: ${{ success() }}
        name: Discord Webhook Notify (Success)
        uses: rjstone/discord-webhook-notify@v2.2.1
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          username: 'Deployment Bot'
          avatarUrl: 'https://github.com/github.png'
          severity: 'info'
          title: 'A new version of Pokedex has been deployed'
          text: to https://full-stack-open-pokedex-billowing-breeze-4348.fly.dev by ${{ github.actor }}

      - if: ${{ failure() }}
        name: Discord Webhook Notify (Failure)
        uses: rjstone/discord-webhook-notify@v2.2.1
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          username: 'Deployment Bot'
          avatarUrl: 'https://github.com/github.png'
          severity: 'error'
          title: 'Build failed'
          text: Commit ${{ github.sha }} by ${{ github.actor }} broke the build :(

  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    if: ${{ needs.simple_deployment_pipeline.outputs.should_deploy == 'true'}}
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
